import { View, Text, ScrollView, StyleSheet, Pressable } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';

export default function TermsOfServiceScreen() {
  const insets = useSafeAreaInsets();

  return (
    <View style={styles.root}>
      <View style={[styles.header, { paddingTop: insets.top + 8 }]}>
        <Pressable onPress={() => router.back()} hitSlop={16} style={styles.backBtn}>
          <Ionicons name="chevron-back" size={22} color="#FFFFFF" />
        </Pressable>
      </View>
      <ScrollView
        contentContainerStyle={[styles.scroll, { paddingBottom: insets.bottom + 40 }]}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.title}>Terms of Service</Text>
        <Text style={styles.updated}>Last updated: April 2026</Text>

        <Text style={styles.body}>
          Welcome to 16TypeTalk. These Terms of Service ("Terms") govern your access to and use of the 16TypeTalk mobile application ("App"). By using the App, you agree to be bound by these Terms.
        </Text>

        <Text style={styles.sectionHeader}>1. ACCEPTANCE OF TERMS</Text>
        <Text style={styles.body}>
          By downloading, installing, or using 16TypeTalk, you acknowledge that you have read, understood, and agree to be bound by these Terms. If you do not agree, please do not use the App.{'\n\n'}
          You must be at least 13 years of age to use this App. If you are under 18, you represent that your parent or legal guardian has reviewed and agreed to these Terms.
        </Text>

        <Text style={styles.sectionHeader}>2. USE OF SERVICE</Text>
        <Text style={styles.body}>
          16TypeTalk provides AI-generated conversations based on MBTI personality type frameworks. The responses are generated by artificial intelligence and are intended for entertainment, self-reflection, and personal exploration purposes only.{'\n\n'}
          <Text style={styles.bold}>AI-generated content is not professional advice.</Text> The personality-based responses should not be considered as professional psychological, medical, legal, or financial advice. Always consult qualified professionals for important decisions.
        </Text>

        <Text style={styles.sectionHeader}>3. USER CONTENT</Text>
        <Text style={styles.body}>
          When you use the App, you may submit topics, questions, or descriptions ("User Content") for discussion by AI personalities. You retain ownership of your User Content.{'\n\n'}
          By submitting User Content, you grant us a limited, non-exclusive license to process your content through our AI service providers solely for the purpose of generating responses during your session. We do not retain or repurpose your User Content after your session ends.{'\n\n'}
          You are solely responsible for the content you submit and agree not to submit content that is illegal, harmful, threatening, abusive, defamatory, or otherwise objectionable.
        </Text>

        <Text style={styles.sectionHeader}>4. PROHIBITED USE</Text>
        <Text style={styles.body}>
          You agree not to:{'\n\n'}
          • Use the App for any unlawful purpose{'\n'}
          • Attempt to interfere with or disrupt the App's functionality{'\n'}
          • Reverse-engineer, decompile, or disassemble the App{'\n'}
          • Use automated scripts or bots to interact with the App{'\n'}
          • Impersonate any person or entity{'\n'}
          • Use the App to generate content that is harmful, hateful, or discriminatory{'\n'}
          • Attempt to extract or harvest data from the App
        </Text>

        <Text style={styles.sectionHeader}>5. DISCLAIMER</Text>
        <Text style={styles.body}>
          <Text style={styles.bold}>IMPORTANT: AI responses generated by 16TypeTalk are not professional psychological advice.</Text>{'\n\n'}
          The App uses MBTI personality type frameworks as a creative tool for self-reflection. The AI personalities are fictional constructs and do not represent real psychological assessments or diagnoses.{'\n\n'}
          The App is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not guarantee the accuracy, completeness, or usefulness of any AI-generated responses.{'\n\n'}
          If you are experiencing psychological distress, please contact a licensed mental health professional or crisis helpline.
        </Text>

        <Text style={styles.sectionHeader}>6. LIMITATION OF LIABILITY</Text>
        <Text style={styles.body}>
          To the maximum extent permitted by applicable law, 16TypeTalk and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or goodwill, arising out of your use of or inability to use the App.
        </Text>

        <Text style={styles.sectionHeader}>7. INTELLECTUAL PROPERTY</Text>
        <Text style={styles.body}>
          The App, including its design, features, content, and underlying technology, is owned by 16TypeTalk and protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works based on the App without our express written permission.
        </Text>

        <Text style={styles.sectionHeader}>8. CHANGES TO TERMS</Text>
        <Text style={styles.body}>
          We reserve the right to modify these Terms at any time. We will notify you of material changes by updating the "Last updated" date. Your continued use of the App after any modifications constitutes acceptance of the updated Terms.
        </Text>

        <Text style={styles.sectionHeader}>9. CONTACT</Text>
        <Text style={styles.body}>
          For questions about these Terms, please contact us at:{'\n\n'}
          contact@16typetalk.app
        </Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#09090D',
  },
  header: {
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF08',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scroll: {
    paddingHorizontal: 24,
  },
  title: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 6,
  },
  updated: {
    color: '#FFFFFF30',
    fontSize: 12,
    marginBottom: 24,
  },
  sectionHeader: {
    color: '#6B5CE7',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.8,
    marginTop: 28,
    marginBottom: 10,
  },
  body: {
    color: '#A0A0B8',
    fontSize: 15,
    lineHeight: 24,
  },
  bold: {
    fontWeight: '600',
    color: '#C0C0D0',
  },
});
